Exercise 6 ready for review
aravindhan-a-cdw/java-exercises pull request #7
Opened 2023-03-06 13:44 UTC by aravindhan-a-cdw

This is a question to calculate time taken by a transport to deliver parcel in destination and displaying the time at the destination timezone.

2023-03-06 15:14 UTC, Adheesh-Sirius requested changes

2023-03-06 15:14 UTC, Adheesh-Sirius commented on exercise_6/DeliveryTimeCalculator.java
> +		System.out.println(ZoneId.getAvailableZoneIds());
Add exception handling while receiving input as the user might provide incorrect values. As you are getting the destination time zone, there might a chance that the user misspells the input.

2023-03-06 15:14 UTC, Adheesh-Sirius commented on exercise_6/DeliveryTimeCalculator.java
> +		Scanner input = new Scanner(System.in);
Please add comments explaining the process. It'll help other developers understand how you are achieving the task

2023-03-08 08:08 UTC, aravindhan-a-cdw commented on exercise_6/DeliveryTimeCalculator.java
> +		System.out.println(ZoneId.getAvailableZoneIds());
Added exception handling for timezone and other inputs from user.

2023-03-08 08:08 UTC, aravindhan-a-cdw commented on exercise_6/DeliveryTimeCalculator.java
> +		Scanner input = new Scanner(System.in);
Added comments and java docs to explain the process handled in the code.

2023-03-09 12:02 UTC, Adheesh-Sirius approved these changes

2023-03-09 12:02 UTC, merged